$ cbl main.bal,listing
      * IBM BASIC ASSEMBLY LANGUAGE - LOW-LEVEL INSTRUCTION SET SIMULATOR
      * DESCRIPTION: SIMULATES INSTRUCTION DECODING, EXECUTION, MEMORY, AND REGISTERS
      AUTHOR: AUTOGENERATED BY ASSISTANT

      SECTION  REG=R
      AMODE    24
      RMODE    24

      * ENTRY POINT
      ENTRY  START,END

START  PROLOG START,SAVEAREA
       USING  *,R14

       * INITIALIZE SIMULATOR STATE
       LA     R1,0          * CLEAR REGISTERS
       ST     R1,REG0
       ST     R1,REG1
       ST     R1,REG2
       ST     R1,REG3
       ST     R1,REG4
       ST     R1,REG5
       ST     R1,REG6
       ST     R1,REG7

       * CLEAR MEMORY (SIMULATED 1000 BYTES)
       LA     R2,MEMSTART
       LA     R3,1000       * SIMULATED MEMORY SIZE
MEMCLR ST     R1,0(R2)     * STORE ZERO TO MEMORY
       BCR    0,7         * ADD ONE TO ADDRESS
       ST     R2,MEMADDR  * UPDATE ADDRESS
       LA     R4,0        * DECREMENT COUNTER
       STH    R4,0(R2)    * STORE COUNTER IF NEEDED
       BCTR   R4,0        * CONTINUE LOOP
       B      MEMCLR

       * LOAD INSTRUCTIONS INTO MEMORY
       * EXAMPLE: LOAD 10 INTO REG0
       MVC    MEMADDR,=F'10'
       ST     R4,INSTRPTR

       * MAIN EXECUTION LOOP
EXLOOP B      DECODER      * JUMP TO DECODER
       B      EXLOOP       * REPEAT

       * INSTRUCTION DECODER
       * FETCH INSTRUCTION FROM MEMORY
       L      R5,INSTRPTR
       LH     R6,0(R5)     * LOAD INSTRUCTION WORD
       SRPG   R7,R6,R6,4   * EXTRACT OP_CODE (ASSUMING 4-BIT OP_CODE)
       * JUMP TO OPERAND-SPECIFIC HANDLERS
       B      HANDLER0      * DEFAULT/JUMP TABLE
       B      HANDLER1
       B      HANDLER2
       B      HANDLER3
       B      HANDLER4
       B      HANDLER5
       B      HANDLER6
       B      HANDLER7
       B      HANDLER8
       B      HANDLER9
       B      HANDLERA
       B      HANDLERB
       B      HANDLERC
       B      HANDLERD
       B      HANDLERE
       B      HANDLERF

       * HANDLER0: LOAD INSTRUCTION (LD Rn, Im)
       * ASSUMES FORMAT: OP_CODE | Rn | Im
       * OP_CODE = 0
       LH     R8,0(R5)     * RELOAD INSTRUCTION
       SR     R8,R8,R8,12  * EXTRACT Rn (4 BITS AT POS 12)
       SR     R9,R8,R8,8   * EXTRACT Im (8 BITS AT POS 8)
       ST     R9,REG0(R8,1) * STORE Im INTO REGn
       B      NEXTINST     * INCREMENT INSTRUCTION POINTER

       * HANDLER1: STORE INSTRUCTION (ST Rn, Im)
       * OP_CODE = 1
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R8,1) * LOAD VALUE FROM REGn
       ST     R10,Im(R5)     * STORE TO MEMORY ADDRESS Im
       B      NEXTINST

       * HANDLER2: ADD INSTRUCTION (AD Rn, Rm)
       * OP_CODE = 2
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R8,1)
       L      R11,REG0(R9,1)
       AR     R10,R11
       ST     R10,REG0(R8,1)
       B      NEXTINST

       * HANDLER3: SUBTRACT INSTRUCTION (SB Rn, Rm)
       * OP_CODE = 3
       LH     R8,0(R5)
       SR     R8,R8,R12
       SR     R9,R8,R8,8
       L      R10,REG0(R8,1)
       L      R11,REG0(R9,1)
       SR     R10,R11
       ST     R10,REG0(R8,1)
       B      NEXTINST

       * HANDLER4: JUMP UNCONDITIONAL (JP Im)
       * OP_CODE = 4
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       LA     R5,Im(R5)     * UPDATE INSTRUCTION POINTER
       B      EXLOOP

       * HANDLER5: JUMP CONDITIONAL (JC Im)
       * OP_CODE = 5
       * CHECK ZERO FLAG OR CARRY FLAG
       * ASSUME ZERO FLAG IN ZEROFLG
       L      R8,ZEROFLG
       BNZ    NOJUMP        * IF NOT ZERO, SKIP JUMP
       LA     R5,Im(R5)     * UPDATE INSTRUCTION POINTER
       B      EXLOOP
NOJUMP B      NEXTINST

       * HANDLER6: HALT INSTRUCTION (HL)
       * OP_CODE = 6
       * EXIT SIMULATOR
       LR     R15,0         * SET RETURN CODE
       BR     R14           * RETURN

       * HANDLER7: INPUT INSTRUCTION (IN Rn)
       * OP_CODE = 7
       * SIMULATE INPUT BY SETTING REGn TO 1
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       LA     R9,1          * SIMULATED INPUT VALUE
       ST     R9,REG0(R8,1)
       B      NEXTINST

       * HANDLER8: OUTPUT INSTRUCTION (OUT Rn)
       * OP_CODE = 8
       * SIMULATE OUTPUT BY PRINTING REGn VALUE
       LH     R8,0(R5)
       L      R9,REG0(R8,1)
       * CALL SYSTEM PRINT SERVICE OR LOG VALUE
       * FOR SIMULATOR, JUST INCREMENT COUNTER TO INDICATE EXECUTION
       LA     R10,OUTCNT
       A      R10,1
       ST     R10,OUTCNT
       B      NEXTINST

       * HANDLER9: MULTIPLY INSTRUCTION (ML Rn, Rm)
       * OP_CODE = 9
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R8,1)
       L      R11,REG0(R9,1)
       ML     R10,R11
       ST     R10,REG0(R8,1)
       B      NEXTINST

       * HANDLERA: DIVIDE INSTRUCTION (DV Rn, Rm)
       * OP_CODE = 10
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R8,1)
       L      R11,REG0(R9,1)
       DV     R10,R11
       ST     R10,REG0(R8,1)
       B      NEXTINST

       * HANDLERB: AND INSTRUCTION (AN Rn, Rm)
       * OP_CODE = 11
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R8,1)
       L      R11,REG0(R9,1)
       NR     R10,R11
       ST     R10,REG0(R8,1)
       B      NEXTINST

       * HANDLERC: OR INSTRUCTION (OR Rn, Rm)
       * OP_CODE = 12
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R8,1)
       L      R11,REG0(R9,1)
       OR     R10,R11
       ST     R10,REG0(R8,1)
       B      NEXTINST

       * HANDLERD: NOT INSTRUCTION (NV Rn)
       * OP_CODE = 13
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       L      R9,REG0(R8,1)
       NI     R9,0          * SIMULATE NOT BY INVERTING BITS
       ST     R9,REG0(R8,1)
       B      NEXTINST

       * HANDLERE: LOAD INDIRECT INSTRUCTION (LI Rn, Rm)
       * OP_CODE = 14
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R9,1) * LOAD ADDRESS FROM REGm
       L      R11,0(R10)     * LOAD VALUE FROM THAT ADDRESS
       ST     R11,REG0(R8,1)
       B      NEXTINST

       * HANDLERF: STORE INDIRECT INSTRUCTION (SI Rn, Rm)
       * OP_CODE = 15
       LH     R8,0(R5)
       SR     R8,R8,R8,12
       SR     R9,R8,R8,8
       L      R10,REG0(R9,1) * LOAD ADDRESS FROM REGm
       L      R11,REG0(R8,1) * LOAD VALUE FROM REGn
       ST     R11,0(R10)     * STORE VALUE TO ADDRESS
       B      NEXTINST

       * NEXT INSTRUCTION HANDLER
NEXTINST LA     R5,INSTRPTR
       A      R5,4          * INCREMENT POINTER BY 4 BYTES
       ST     R5,INSTRPTR   * UPDATE POINTER
       B      EXLOOP        * CONTINUE EXECUTION

       * DATA AREA
SAVEAREA DS     18F          * SAVE AREA FOR LINKAGE
REG0     DS     256F        * REGISTER FILE (64 REGISTERS * 4 BYTES)
MEMSTART EQU    * START OF SIMULATED MEMORY
MEMADDR  DS     F           * CURRENT MEMORY ADDRESS
INSTRPTR DS     F           * INSTRUCTION POINTER
ZEROFLG  DS     F           * ZERO FLAG
OUTCNT   DS     F           * OUTPUT COUNTER
ENDCNT   EQU    * END OF DATA

       * END OF PROGRAM
END    EPILOG END

       END START,END
