(* ML Tool: Functional Language Compiler Backend *)

(* Type definitions *)
type expr =
  | Var of string
  | Lit of int
  | BinOp of expr * string * expr
  | Lambda of string * expr
  | App of expr * expr

type env = (string * int) list

(* Type inference engine *)
type ty =
  | TInt
  | TBool
  | TArrow of ty * ty

type env_ty = (string * ty) list

type infer_result = ty * expr

type infer_error =
  | TypeError of string
  | UnboundVar of string
  | Mismatch of ty * ty

let rec lookup_tenv env_ty x =
  match env_ty with
  | [] -> raise (UnboundVar x)
  | (name, ty) :: rest -> if name = x then ty else lookup_tenv rest x

let rec infer expr env_ty =
  match expr with
  | Var x -> lookup_tenv env_ty x
  | Lit _ -> TInt
  | BinOp (e1, op, e2) ->
      let ty1 = infer e1 env_ty in
      let ty2 = infer e2 env_ty in
      match (ty1, ty2, op) with
      | (TInt, TInt, "+") -> TInt
      | (TInt, TInt, "-") -> TInt
      | (TInt, TInt, "*") -> TInt
      | _ -> raise (Mismatch (ty1, ty2))
  | Lambda (x, body) ->
      let body_ty = infer body ((x, TInt) :: env_ty) in
      TArrow (TInt, body_ty)
  | App (f, arg) ->
      let f_ty = infer f env_ty in
      let arg_ty = infer arg env_ty in
      match f_ty with
      | TArrow (arg, ret) ->
          if arg = arg_ty then ret
          else raise (Mismatch (arg, arg_ty))
      | _ -> raise (Mismatch (f_ty, arg_ty))

(* Code generation *)
type bytecode =
  | Push of int
  | Call of string
  | Return

let rec generate_code expr env =
  match expr with
  | Var x -> [Call x]
  | Lit n -> [Push n]
  | BinOp (e1, _, e2) ->
      generate_code e1 env @ generate_code e2 env @ [Return]
  | Lambda (x, body) ->
      generate_code body ((x, Push 0) :: env) @ [Return]
  | App (f, arg) ->
      generate_code arg env @ generate_code f env @ [Return]

(* Example usage *)
let example_expr = App (Lambda ("x", BinOp (Var "x", "+", Lit 1)), Lit 5)

let () =
  try
    let ty = infer example_expr [] in
    Printf.printf "Inferred type: %s\n" (match ty with TInt -> "int" | _ -> "other");
    let code = generate_code example_expr [] in
    Printf.printf "Generated bytecode: %s\n" (String.concat " " (List.map (function Push n -> "Push " ^ string_of_int n | Call x -> "Call " ^ x | Return -> "Return") code))
  with
  | UnboundVar x -> Printf.printf "Error: Unbound variable %s\n" x
  | Mismatch (t1, t2) -> Printf.printf "Error: Type mismatch %s vs %s\n" (match t1 with TInt -> "int" | _ -> "other") (match t2 with TInt -> "int" | _ -> "other")
